DROP TABLE IF EXISTS Invoices
GO
DROP TABLE IF EXISTS Clients
GO

CREATE TABLE Clients (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    BusinessName NVARCHAR(100) NOT NULL,
    CUIT VARCHAR(15) NOT NULL,
    IsActive BIT NOT NULL,
    ActivationDate DATETIME NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Phone NVARCHAR(20) NOT NULL,
    Address NVARCHAR(150) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    Province NVARCHAR(100) NOT NULL
	CONSTRAINT UK_BusinessName UNIQUE (BusinessName)
)
GO

CREATE TABLE Invoices (
    Id INT PRIMARY KEY IDENTITY(1,1),
    ClientId INT NOT NULL,
    Date DATETIME NOT NULL,
    TotalAmount DECIMAL(18, 2) NOT NULL,
    IsPaid BIT NOT NULL,
    CONSTRAINT FK_Invoices_Clients FOREIGN KEY (ClientId) REFERENCES Clients(Id),
)
GO
